### ISSUE TITLE
你看我写的这个相声能提个MR吗（和程序员的关系呢，我是程序员 😂）

### ISSUE THREAD

**Issue by shuiRong** [koolob/programmer-crosstalk#1]
地址一：https://www.v2ex.com/t/531922#reply4
地址二：https://linshuirong.cn/2019/01/30/%E7%9B%B8%E5%A3%B0%EF%BC%9A%E4%B8%80%E4%B8%AA%E4%BC%91%E5%AD%A6%E7%9A%84%E5%AE%9E%E4%B9%A0%E7%94%9F%E7%9A%84%E8%A2%AB%E8%A3%81%E7%BB%8F%E5%8E%86/

**Comment by koolob** [comment]
这边主要还是接收程序员主题的相声。
